/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_equipement_ajouter (void);
GtkWidget* create_equipement_modifier (void);
GtkWidget* create_equipement_afficher (void);
GtkWidget* create_equipement_supprimer (void);
GtkWidget* create_capteurs_alarmants (void);
