/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_equipement_ajouter (void)
{
  GtkWidget *equipement_ajouter;
  GtkWidget *fixed1;
  GtkWidget *numaj;
  GtkWidget *typeaj;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *eventbox4;
  GtkWidget *button5calendrier_aj;
  GtkWidget *eventbox6;
  GtkWidget *button4troupeaux_aj;
  GtkWidget *eventbox9;
  GtkWidget *button2ouvrier_aj;
  GtkWidget *eventbox10;
  GtkWidget *button3client_aj;
  GtkWidget *eventbox11;
  GtkWidget *button1capteurs_aj;
  GtkWidget *eventbox12;
  GtkWidget *button8supprimer_aj;
  GtkWidget *eventbox13;
  GtkWidget *button7afficher_aj;
  GtkWidget *eventbox14;
  GtkWidget *button6modifier_aj;
  GtkWidget *eventbox15;
  GtkWidget *combobox1;
  GtkWidget *eventbox16;
  GtkWidget *label29dent_aj;
  GtkWidget *eventbox17;
  GtkWidget *label28dach_aj;
  GtkWidget *eventbox18;
  GtkWidget *label17etat_aj;
  GtkWidget *eventbox19;
  GtkWidget *label16type_aj;
  GtkWidget *eventbox20;
  GtkWidget *label15numdeserie_aj;
  GtkWidget *image4;
  GtkWidget *eventbox29;
  GtkWidget *button55ajouter_aj;
  GtkWidget *eventbox30;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label27;

  equipement_ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (equipement_ajouter, 1100, 600);
  gtk_window_set_title (GTK_WINDOW (equipement_ajouter), _("espace employ\303\251"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (equipement_ajouter), fixed1);

  numaj = gtk_entry_new ();
  gtk_widget_show (numaj);
  gtk_fixed_put (GTK_FIXED (fixed1), numaj, 440, 240);
  gtk_widget_set_size_request (numaj, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (numaj), 8226);

  typeaj = gtk_entry_new ();
  gtk_widget_show (typeaj);
  gtk_fixed_put (GTK_FIXED (fixed1), typeaj, 440, 296);
  gtk_widget_set_size_request (typeaj, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (typeaj), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton1, 408, 504);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton2, 504, 504);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (1, 2020, 2050, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton3, 608, 504);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  spinbutton4_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton4, 408, 432);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  spinbutton5_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton5, 504, 432);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (1, 2020, 2050, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton6, 608, 432);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  eventbox4 = gtk_event_box_new ();
  gtk_widget_show (eventbox4);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox4, 696, 128);
  gtk_widget_set_size_request (eventbox4, 80, 32);

  button5calendrier_aj = gtk_button_new_with_mnemonic (_("calendrier"));
  gtk_widget_show (button5calendrier_aj);
  gtk_container_add (GTK_CONTAINER (eventbox4), button5calendrier_aj);
  gtk_widget_set_size_request (button5calendrier_aj, 80, 32);

  eventbox6 = gtk_event_box_new ();
  gtk_widget_show (eventbox6);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox6, 384, 128);
  gtk_widget_set_size_request (eventbox6, 80, 32);

  button4troupeaux_aj = gtk_button_new_with_mnemonic (_("troupeaux"));
  gtk_widget_show (button4troupeaux_aj);
  gtk_container_add (GTK_CONTAINER (eventbox6), button4troupeaux_aj);
  gtk_widget_set_size_request (button4troupeaux_aj, 80, 32);

  eventbox9 = gtk_event_box_new ();
  gtk_widget_show (eventbox9);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox9, 592, 128);
  gtk_widget_set_size_request (eventbox9, 80, 32);

  button2ouvrier_aj = gtk_button_new_with_mnemonic (_("ouvrier"));
  gtk_widget_show (button2ouvrier_aj);
  gtk_container_add (GTK_CONTAINER (eventbox9), button2ouvrier_aj);
  gtk_widget_set_size_request (button2ouvrier_aj, 80, 32);

  eventbox10 = gtk_event_box_new ();
  gtk_widget_show (eventbox10);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox10, 800, 128);
  gtk_widget_set_size_request (eventbox10, 80, 32);

  button3client_aj = gtk_button_new_with_mnemonic (_("clients"));
  gtk_widget_show (button3client_aj);
  gtk_container_add (GTK_CONTAINER (eventbox10), button3client_aj);
  gtk_widget_set_size_request (button3client_aj, 80, 32);

  eventbox11 = gtk_event_box_new ();
  gtk_widget_show (eventbox11);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox11, 280, 128);
  gtk_widget_set_size_request (eventbox11, 80, 32);

  button1capteurs_aj = gtk_button_new_with_mnemonic (_("capteurs"));
  gtk_widget_show (button1capteurs_aj);
  gtk_container_add (GTK_CONTAINER (eventbox11), button1capteurs_aj);
  gtk_widget_set_size_request (button1capteurs_aj, 80, 32);

  eventbox12 = gtk_event_box_new ();
  gtk_widget_show (eventbox12);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox12, 16, 424);
  gtk_widget_set_size_request (eventbox12, 168, 44);

  button8supprimer_aj = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (button8supprimer_aj);
  gtk_container_add (GTK_CONTAINER (eventbox12), button8supprimer_aj);
  gtk_widget_set_size_request (button8supprimer_aj, 168, 44);

  eventbox13 = gtk_event_box_new ();
  gtk_widget_show (eventbox13);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox13, 16, 352);
  gtk_widget_set_size_request (eventbox13, 168, 44);

  button7afficher_aj = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (button7afficher_aj);
  gtk_container_add (GTK_CONTAINER (eventbox13), button7afficher_aj);
  gtk_widget_set_size_request (button7afficher_aj, 168, 44);

  eventbox14 = gtk_event_box_new ();
  gtk_widget_show (eventbox14);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox14, 16, 280);
  gtk_widget_set_size_request (eventbox14, 168, 44);

  button6modifier_aj = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (button6modifier_aj);
  gtk_container_add (GTK_CONTAINER (eventbox14), button6modifier_aj);
  gtk_widget_set_size_request (button6modifier_aj, 168, 44);

  eventbox15 = gtk_event_box_new ();
  gtk_widget_show (eventbox15);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox15, 440, 360);
  gtk_widget_set_size_request (eventbox15, 160, 32);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_container_add (GTK_CONTAINER (eventbox15), combobox1);
  gtk_widget_set_size_request (combobox1, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("neuf"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("occasion"));

  eventbox16 = gtk_event_box_new ();
  gtk_widget_show (eventbox16);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox16, 256, 504);
  gtk_widget_set_size_request (eventbox16, 128, 32);

  label29dent_aj = gtk_label_new (_("date d'entretien"));
  gtk_widget_show (label29dent_aj);
  gtk_container_add (GTK_CONTAINER (eventbox16), label29dent_aj);
  gtk_widget_set_size_request (label29dent_aj, 128, 32);

  eventbox17 = gtk_event_box_new ();
  gtk_widget_show (eventbox17);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox17, 256, 432);
  gtk_widget_set_size_request (eventbox17, 137, 33);

  label28dach_aj = gtk_label_new (_("date d'achat"));
  gtk_widget_show (label28dach_aj);
  gtk_container_add (GTK_CONTAINER (eventbox17), label28dach_aj);
  gtk_widget_set_size_request (label28dach_aj, 137, 33);

  eventbox18 = gtk_event_box_new ();
  gtk_widget_show (eventbox18);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox18, 288, 360);
  gtk_widget_set_size_request (eventbox18, 88, 30);

  label17etat_aj = gtk_label_new (_("Etat"));
  gtk_widget_show (label17etat_aj);
  gtk_container_add (GTK_CONTAINER (eventbox18), label17etat_aj);
  gtk_widget_set_size_request (label17etat_aj, 88, 30);

  eventbox19 = gtk_event_box_new ();
  gtk_widget_show (eventbox19);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox19, 272, 296);
  gtk_widget_set_size_request (eventbox19, 120, 30);

  label16type_aj = gtk_label_new (_("type :"));
  gtk_widget_show (label16type_aj);
  gtk_container_add (GTK_CONTAINER (eventbox19), label16type_aj);
  gtk_widget_set_size_request (label16type_aj, 120, 30);

  eventbox20 = gtk_event_box_new ();
  gtk_widget_show (eventbox20);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox20, 248, 240);
  gtk_widget_set_size_request (eventbox20, 160, 30);

  label15numdeserie_aj = gtk_label_new (_("numero de serie :"));
  gtk_widget_show (label15numdeserie_aj);
  gtk_container_add (GTK_CONTAINER (eventbox20), label15numdeserie_aj);
  gtk_widget_set_size_request (label15numdeserie_aj, 160, 30);

  image4 = create_pixmap (equipement_ajouter, "ajouter1.jpg");
  gtk_widget_show (image4);
  gtk_fixed_put (GTK_FIXED (fixed1), image4, 0, 0);
  gtk_widget_set_size_request (image4, 1104, 608);

  eventbox29 = gtk_event_box_new ();
  gtk_widget_show (eventbox29);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox29, 680, 336);
  gtk_widget_set_size_request (eventbox29, 136, 48);

  button55ajouter_aj = gtk_button_new ();
  gtk_widget_show (button55ajouter_aj);
  gtk_container_add (GTK_CONTAINER (eventbox29), button55ajouter_aj);
  gtk_widget_set_size_request (button55ajouter_aj, 136, 48);

  eventbox30 = gtk_event_box_new ();
  gtk_widget_show (eventbox30);
  gtk_container_add (GTK_CONTAINER (button55ajouter_aj), eventbox30);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (eventbox30), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox3), label27, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button5calendrier_aj, "clicked",
                    G_CALLBACK (on_button5calendrier_aj_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4troupeaux_aj, "clicked",
                    G_CALLBACK (on_button4troupeauxaj_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2ouvrier_aj, "clicked",
                    G_CALLBACK (on_button2ouvrier_aj_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3client_aj, "clicked",
                    G_CALLBACK (on_button3clientaj_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1capteurs_aj, "clicked",
                    G_CALLBACK (on_button1capteursaj_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8supprimer_aj, "clicked",
                    G_CALLBACK (on_button8supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7afficher_aj, "clicked",
                    G_CALLBACK (on_button7afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6modifier_aj, "clicked",
                    G_CALLBACK (on_button6modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button55ajouter_aj, "clicked",
                    G_CALLBACK (on_button55ajouter_aj_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (equipement_ajouter, equipement_ajouter, "equipement_ajouter");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, numaj, "numaj");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, typeaj, "typeaj");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, eventbox4, "eventbox4");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, button5calendrier_aj, "button5calendrier_aj");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, eventbox6, "eventbox6");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, button4troupeaux_aj, "button4troupeaux_aj");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, eventbox9, "eventbox9");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, button2ouvrier_aj, "button2ouvrier_aj");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, eventbox10, "eventbox10");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, button3client_aj, "button3client_aj");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, eventbox11, "eventbox11");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, button1capteurs_aj, "button1capteurs_aj");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, eventbox12, "eventbox12");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, button8supprimer_aj, "button8supprimer_aj");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, eventbox13, "eventbox13");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, button7afficher_aj, "button7afficher_aj");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, eventbox14, "eventbox14");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, button6modifier_aj, "button6modifier_aj");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, eventbox15, "eventbox15");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, eventbox16, "eventbox16");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, label29dent_aj, "label29dent_aj");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, eventbox17, "eventbox17");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, label28dach_aj, "label28dach_aj");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, eventbox18, "eventbox18");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, label17etat_aj, "label17etat_aj");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, eventbox19, "eventbox19");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, label16type_aj, "label16type_aj");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, eventbox20, "eventbox20");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, label15numdeserie_aj, "label15numdeserie_aj");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, image4, "image4");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, eventbox29, "eventbox29");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, button55ajouter_aj, "button55ajouter_aj");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, eventbox30, "eventbox30");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, image3, "image3");
  GLADE_HOOKUP_OBJECT (equipement_ajouter, label27, "label27");

  return equipement_ajouter;
}

GtkWidget*
create_equipement_modifier (void)
{
  GtkWidget *equipement_modifier;
  GtkWidget *fixed2;
  GtkWidget *nummo;
  GtkWidget *typemod;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkObject *spinbutton9_adj;
  GtkWidget *spinbutton9;
  GtkObject *spinbutton10_adj;
  GtkWidget *spinbutton10;
  GtkObject *spinbutton11_adj;
  GtkWidget *spinbutton11;
  GtkObject *spinbutton12_adj;
  GtkWidget *spinbutton12;
  GtkWidget *eventbox22;
  GtkWidget *label23numdeserie_mod;
  GtkWidget *eventbox23;
  GtkWidget *label24type_mod;
  GtkWidget *eventbox24;
  GtkWidget *label25etat_mod;
  GtkWidget *eventbox25;
  GtkWidget *label28;
  GtkWidget *eventbox26;
  GtkWidget *label29;
  GtkWidget *eventbox27;
  GtkWidget *combobox2;
  GtkWidget *eventbox31;
  GtkWidget *button57modifier_mod;
  GtkWidget *eventbox28;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label26;
  GtkWidget *eventbox33;
  GtkWidget *button15ouvriermod;
  GtkWidget *eventbox34;
  GtkWidget *button16capteursmod;
  GtkWidget *eventbox35;
  GtkWidget *button14clientsmod;
  GtkWidget *eventbox36;
  GtkWidget *button12calendriermod;
  GtkWidget *eventbox37;
  GtkWidget *button13troupeauxmod;
  GtkWidget *eventbox38;
  GtkWidget *button17ajoutermod;
  GtkWidget *eventbox39;
  GtkWidget *button10;
  GtkWidget *eventbox40;
  GtkWidget *button9;
  GtkWidget *image5;

  equipement_modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (equipement_modifier), _("espace employ\303\251"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (equipement_modifier), fixed2);

  nummo = gtk_entry_new ();
  gtk_widget_show (nummo);
  gtk_fixed_put (GTK_FIXED (fixed2), nummo, 440, 240);
  gtk_widget_set_size_request (nummo, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nummo), 8226);

  typemod = gtk_entry_new ();
  gtk_widget_show (typemod);
  gtk_fixed_put (GTK_FIXED (fixed2), typemod, 440, 296);
  gtk_widget_set_size_request (typemod, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (typemod), 8226);

  spinbutton7_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton7, 408, 432);
  gtk_widget_set_size_request (spinbutton7, 60, 27);

  spinbutton8_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 0);
  gtk_widget_show (spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton8, 504, 432);
  gtk_widget_set_size_request (spinbutton8, 60, 27);

  spinbutton9_adj = gtk_adjustment_new (1, 2020, 2050, 1, 10, 10);
  spinbutton9 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton9_adj), 1, 0);
  gtk_widget_show (spinbutton9);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton9, 608, 432);
  gtk_widget_set_size_request (spinbutton9, 60, 27);

  spinbutton10_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton10 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton10_adj), 1, 0);
  gtk_widget_show (spinbutton10);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton10, 408, 504);
  gtk_widget_set_size_request (spinbutton10, 60, 27);

  spinbutton11_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton11 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton11_adj), 1, 0);
  gtk_widget_show (spinbutton11);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton11, 504, 504);
  gtk_widget_set_size_request (spinbutton11, 60, 27);

  spinbutton12_adj = gtk_adjustment_new (1, 2020, 2050, 1, 10, 10);
  spinbutton12 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton12_adj), 1, 0);
  gtk_widget_show (spinbutton12);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton12, 608, 504);
  gtk_widget_set_size_request (spinbutton12, 60, 27);

  eventbox22 = gtk_event_box_new ();
  gtk_widget_show (eventbox22);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox22, 264, 240);
  gtk_widget_set_size_request (eventbox22, 144, 32);

  label23numdeserie_mod = gtk_label_new (_("Numero  de serie\n       a modifier"));
  gtk_widget_show (label23numdeserie_mod);
  gtk_container_add (GTK_CONTAINER (eventbox22), label23numdeserie_mod);
  gtk_widget_set_size_request (label23numdeserie_mod, 144, 32);

  eventbox23 = gtk_event_box_new ();
  gtk_widget_show (eventbox23);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox23, 288, 296);
  gtk_widget_set_size_request (eventbox23, 97, 33);

  label24type_mod = gtk_label_new (_("type"));
  gtk_widget_show (label24type_mod);
  gtk_container_add (GTK_CONTAINER (eventbox23), label24type_mod);
  gtk_widget_set_size_request (label24type_mod, 97, 33);

  eventbox24 = gtk_event_box_new ();
  gtk_widget_show (eventbox24);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox24, 304, 360);
  gtk_widget_set_size_request (eventbox24, 80, 32);

  label25etat_mod = gtk_label_new (_("Etat"));
  gtk_widget_show (label25etat_mod);
  gtk_container_add (GTK_CONTAINER (eventbox24), label25etat_mod);
  gtk_widget_set_size_request (label25etat_mod, 80, 32);

  eventbox25 = gtk_event_box_new ();
  gtk_widget_show (eventbox25);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox25, 264, 432);
  gtk_widget_set_size_request (eventbox25, 112, 32);

  label28 = gtk_label_new (_("date d'achat"));
  gtk_widget_show (label28);
  gtk_container_add (GTK_CONTAINER (eventbox25), label28);
  gtk_widget_set_size_request (label28, 112, 32);

  eventbox26 = gtk_event_box_new ();
  gtk_widget_show (eventbox26);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox26, 256, 496);
  gtk_widget_set_size_request (eventbox26, 128, 40);

  label29 = gtk_label_new (_("date d'entretien"));
  gtk_widget_show (label29);
  gtk_container_add (GTK_CONTAINER (eventbox26), label29);
  gtk_widget_set_size_request (label29, 128, 40);

  eventbox27 = gtk_event_box_new ();
  gtk_widget_show (eventbox27);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox27, 440, 360);
  gtk_widget_set_size_request (eventbox27, 160, 32);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_container_add (GTK_CONTAINER (eventbox27), combobox2);
  gtk_widget_set_size_request (combobox2, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("neuf"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("occasion"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("en panne"));

  eventbox31 = gtk_event_box_new ();
  gtk_widget_show (eventbox31);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox31, 688, 328);
  gtk_widget_set_size_request (eventbox31, 136, 48);

  button57modifier_mod = gtk_button_new ();
  gtk_widget_show (button57modifier_mod);
  gtk_container_add (GTK_CONTAINER (eventbox31), button57modifier_mod);
  gtk_widget_set_size_request (button57modifier_mod, 136, 48);

  eventbox28 = gtk_event_box_new ();
  gtk_widget_show (eventbox28);
  gtk_container_add (GTK_CONTAINER (button57modifier_mod), eventbox28);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (eventbox28), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox2), label26, FALSE, FALSE, 0);

  eventbox33 = gtk_event_box_new ();
  gtk_widget_show (eventbox33);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox33, 592, 128);
  gtk_widget_set_size_request (eventbox33, 80, 32);

  button15ouvriermod = gtk_button_new_with_mnemonic (_("ouvrier"));
  gtk_widget_show (button15ouvriermod);
  gtk_container_add (GTK_CONTAINER (eventbox33), button15ouvriermod);
  gtk_widget_set_size_request (button15ouvriermod, 80, 32);

  eventbox34 = gtk_event_box_new ();
  gtk_widget_show (eventbox34);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox34, 280, 128);
  gtk_widget_set_size_request (eventbox34, 80, 32);

  button16capteursmod = gtk_button_new_with_mnemonic (_("capteurs"));
  gtk_widget_show (button16capteursmod);
  gtk_container_add (GTK_CONTAINER (eventbox34), button16capteursmod);
  gtk_widget_set_size_request (button16capteursmod, 80, 32);

  eventbox35 = gtk_event_box_new ();
  gtk_widget_show (eventbox35);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox35, 800, 128);
  gtk_widget_set_size_request (eventbox35, 80, 32);

  button14clientsmod = gtk_button_new_with_mnemonic (_("clients"));
  gtk_widget_show (button14clientsmod);
  gtk_container_add (GTK_CONTAINER (eventbox35), button14clientsmod);
  gtk_widget_set_size_request (button14clientsmod, 80, 32);

  eventbox36 = gtk_event_box_new ();
  gtk_widget_show (eventbox36);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox36, 696, 128);
  gtk_widget_set_size_request (eventbox36, 80, 32);

  button12calendriermod = gtk_button_new_with_mnemonic (_("calendrier"));
  gtk_widget_show (button12calendriermod);
  gtk_container_add (GTK_CONTAINER (eventbox36), button12calendriermod);
  gtk_widget_set_size_request (button12calendriermod, 80, 32);

  eventbox37 = gtk_event_box_new ();
  gtk_widget_show (eventbox37);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox37, 384, 128);
  gtk_widget_set_size_request (eventbox37, 80, 32);

  button13troupeauxmod = gtk_button_new_with_mnemonic (_("troupeaux"));
  gtk_widget_show (button13troupeauxmod);
  gtk_container_add (GTK_CONTAINER (eventbox37), button13troupeauxmod);
  gtk_widget_set_size_request (button13troupeauxmod, 80, 32);

  eventbox38 = gtk_event_box_new ();
  gtk_widget_show (eventbox38);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox38, 16, 208);
  gtk_widget_set_size_request (eventbox38, 168, 44);

  button17ajoutermod = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (button17ajoutermod);
  gtk_container_add (GTK_CONTAINER (eventbox38), button17ajoutermod);
  gtk_widget_set_size_request (button17ajoutermod, 168, 44);

  eventbox39 = gtk_event_box_new ();
  gtk_widget_show (eventbox39);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox39, 16, 352);
  gtk_widget_set_size_request (eventbox39, 168, 44);

  button10 = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (button10);
  gtk_container_add (GTK_CONTAINER (eventbox39), button10);
  gtk_widget_set_size_request (button10, 168, 44);

  eventbox40 = gtk_event_box_new ();
  gtk_widget_show (eventbox40);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox40, 16, 424);
  gtk_widget_set_size_request (eventbox40, 168, 44);

  button9 = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (button9);
  gtk_container_add (GTK_CONTAINER (eventbox40), button9);
  gtk_widget_set_size_request (button9, 168, 44);

  image5 = create_pixmap (equipement_modifier, "modifier2.jpg");
  gtk_widget_show (image5);
  gtk_fixed_put (GTK_FIXED (fixed2), image5, 0, 0);
  gtk_widget_set_size_request (image5, 1104, 608);

  g_signal_connect ((gpointer) button57modifier_mod, "clicked",
                    G_CALLBACK (on_button57modifier_mod_clicked),
                    NULL);
  g_signal_connect ((gpointer) button15ouvriermod, "clicked",
                    G_CALLBACK (on_button15ouvriermod_clicked),
                    NULL);
  g_signal_connect ((gpointer) button16capteursmod, "clicked",
                    G_CALLBACK (on_button16capteursmod_clicked),
                    NULL);
  g_signal_connect ((gpointer) button14clientsmod, "clicked",
                    G_CALLBACK (on_button14clientsmod_clicked),
                    NULL);
  g_signal_connect ((gpointer) button12calendriermod, "clicked",
                    G_CALLBACK (on_button12calendriermod_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13troupeauxmod, "clicked",
                    G_CALLBACK (on_button13troupeauxmod_clicked),
                    NULL);
  g_signal_connect ((gpointer) button17ajoutermod, "clicked",
                    G_CALLBACK (on_button17ajoutermod_clicked),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_button10_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (equipement_modifier, equipement_modifier, "equipement_modifier");
  GLADE_HOOKUP_OBJECT (equipement_modifier, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (equipement_modifier, nummo, "nummo");
  GLADE_HOOKUP_OBJECT (equipement_modifier, typemod, "typemod");
  GLADE_HOOKUP_OBJECT (equipement_modifier, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (equipement_modifier, spinbutton8, "spinbutton8");
  GLADE_HOOKUP_OBJECT (equipement_modifier, spinbutton9, "spinbutton9");
  GLADE_HOOKUP_OBJECT (equipement_modifier, spinbutton10, "spinbutton10");
  GLADE_HOOKUP_OBJECT (equipement_modifier, spinbutton11, "spinbutton11");
  GLADE_HOOKUP_OBJECT (equipement_modifier, spinbutton12, "spinbutton12");
  GLADE_HOOKUP_OBJECT (equipement_modifier, eventbox22, "eventbox22");
  GLADE_HOOKUP_OBJECT (equipement_modifier, label23numdeserie_mod, "label23numdeserie_mod");
  GLADE_HOOKUP_OBJECT (equipement_modifier, eventbox23, "eventbox23");
  GLADE_HOOKUP_OBJECT (equipement_modifier, label24type_mod, "label24type_mod");
  GLADE_HOOKUP_OBJECT (equipement_modifier, eventbox24, "eventbox24");
  GLADE_HOOKUP_OBJECT (equipement_modifier, label25etat_mod, "label25etat_mod");
  GLADE_HOOKUP_OBJECT (equipement_modifier, eventbox25, "eventbox25");
  GLADE_HOOKUP_OBJECT (equipement_modifier, label28, "label28");
  GLADE_HOOKUP_OBJECT (equipement_modifier, eventbox26, "eventbox26");
  GLADE_HOOKUP_OBJECT (equipement_modifier, label29, "label29");
  GLADE_HOOKUP_OBJECT (equipement_modifier, eventbox27, "eventbox27");
  GLADE_HOOKUP_OBJECT (equipement_modifier, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (equipement_modifier, eventbox31, "eventbox31");
  GLADE_HOOKUP_OBJECT (equipement_modifier, button57modifier_mod, "button57modifier_mod");
  GLADE_HOOKUP_OBJECT (equipement_modifier, eventbox28, "eventbox28");
  GLADE_HOOKUP_OBJECT (equipement_modifier, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (equipement_modifier, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (equipement_modifier, image2, "image2");
  GLADE_HOOKUP_OBJECT (equipement_modifier, label26, "label26");
  GLADE_HOOKUP_OBJECT (equipement_modifier, eventbox33, "eventbox33");
  GLADE_HOOKUP_OBJECT (equipement_modifier, button15ouvriermod, "button15ouvriermod");
  GLADE_HOOKUP_OBJECT (equipement_modifier, eventbox34, "eventbox34");
  GLADE_HOOKUP_OBJECT (equipement_modifier, button16capteursmod, "button16capteursmod");
  GLADE_HOOKUP_OBJECT (equipement_modifier, eventbox35, "eventbox35");
  GLADE_HOOKUP_OBJECT (equipement_modifier, button14clientsmod, "button14clientsmod");
  GLADE_HOOKUP_OBJECT (equipement_modifier, eventbox36, "eventbox36");
  GLADE_HOOKUP_OBJECT (equipement_modifier, button12calendriermod, "button12calendriermod");
  GLADE_HOOKUP_OBJECT (equipement_modifier, eventbox37, "eventbox37");
  GLADE_HOOKUP_OBJECT (equipement_modifier, button13troupeauxmod, "button13troupeauxmod");
  GLADE_HOOKUP_OBJECT (equipement_modifier, eventbox38, "eventbox38");
  GLADE_HOOKUP_OBJECT (equipement_modifier, button17ajoutermod, "button17ajoutermod");
  GLADE_HOOKUP_OBJECT (equipement_modifier, eventbox39, "eventbox39");
  GLADE_HOOKUP_OBJECT (equipement_modifier, button10, "button10");
  GLADE_HOOKUP_OBJECT (equipement_modifier, eventbox40, "eventbox40");
  GLADE_HOOKUP_OBJECT (equipement_modifier, button9, "button9");
  GLADE_HOOKUP_OBJECT (equipement_modifier, image5, "image5");

  return equipement_modifier;
}

GtkWidget*
create_equipement_afficher (void)
{
  GtkWidget *equipement_afficher;
  GtkWidget *fixed3;
  GtkWidget *treeview1;
  GtkWidget *entryfiltre;
  GtkWidget *eventbox51;
  GtkWidget *button29capteurs_aff;
  GtkWidget *eventbox52;
  GtkWidget *button26troupeaux_aff;
  GtkWidget *eventbox53;
  GtkWidget *button25calendrier_aff;
  GtkWidget *eventbox54;
  GtkWidget *button28ouvrier_aff;
  GtkWidget *eventbox55;
  GtkWidget *button27clients_aff;
  GtkWidget *eventbox56;
  GtkWidget *button32ajouter_aff;
  GtkWidget *eventbox57;
  GtkWidget *button24modifier_aff;
  GtkWidget *eventbox58;
  GtkWidget *button22supprimer_aff;
  GtkWidget *image7;
  GtkWidget *eventbox59;
  GtkWidget *button44;

  equipement_afficher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (equipement_afficher), _("espace employ\303\251"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (equipement_afficher), fixed3);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1, 224, 256);
  gtk_widget_set_size_request (treeview1, 608, 320);

  entryfiltre = gtk_entry_new ();
  gtk_widget_show (entryfiltre);
  gtk_fixed_put (GTK_FIXED (fixed3), entryfiltre, 448, 208);
  gtk_widget_set_size_request (entryfiltre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryfiltre), 8226);

  eventbox51 = gtk_event_box_new ();
  gtk_widget_show (eventbox51);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox51, 280, 128);
  gtk_widget_set_size_request (eventbox51, 80, 32);

  button29capteurs_aff = gtk_button_new_with_mnemonic (_("capteurs"));
  gtk_widget_show (button29capteurs_aff);
  gtk_container_add (GTK_CONTAINER (eventbox51), button29capteurs_aff);
  gtk_widget_set_size_request (button29capteurs_aff, 80, 32);

  eventbox52 = gtk_event_box_new ();
  gtk_widget_show (eventbox52);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox52, 384, 128);
  gtk_widget_set_size_request (eventbox52, 80, 32);

  button26troupeaux_aff = gtk_button_new_with_mnemonic (_("troupeaux"));
  gtk_widget_show (button26troupeaux_aff);
  gtk_container_add (GTK_CONTAINER (eventbox52), button26troupeaux_aff);
  gtk_widget_set_size_request (button26troupeaux_aff, 80, 32);

  eventbox53 = gtk_event_box_new ();
  gtk_widget_show (eventbox53);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox53, 696, 128);
  gtk_widget_set_size_request (eventbox53, 80, 32);

  button25calendrier_aff = gtk_button_new_with_mnemonic (_("calendrier"));
  gtk_widget_show (button25calendrier_aff);
  gtk_container_add (GTK_CONTAINER (eventbox53), button25calendrier_aff);
  gtk_widget_set_size_request (button25calendrier_aff, 80, 32);

  eventbox54 = gtk_event_box_new ();
  gtk_widget_show (eventbox54);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox54, 592, 128);
  gtk_widget_set_size_request (eventbox54, 80, 32);

  button28ouvrier_aff = gtk_button_new_with_mnemonic (_("ouvrier"));
  gtk_widget_show (button28ouvrier_aff);
  gtk_container_add (GTK_CONTAINER (eventbox54), button28ouvrier_aff);
  gtk_widget_set_size_request (button28ouvrier_aff, 80, 32);

  eventbox55 = gtk_event_box_new ();
  gtk_widget_show (eventbox55);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox55, 800, 128);
  gtk_widget_set_size_request (eventbox55, 80, 32);

  button27clients_aff = gtk_button_new_with_mnemonic (_("clients"));
  gtk_widget_show (button27clients_aff);
  gtk_container_add (GTK_CONTAINER (eventbox55), button27clients_aff);
  gtk_widget_set_size_request (button27clients_aff, 80, 32);

  eventbox56 = gtk_event_box_new ();
  gtk_widget_show (eventbox56);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox56, 16, 208);
  gtk_widget_set_size_request (eventbox56, 168, 44);

  button32ajouter_aff = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (button32ajouter_aff);
  gtk_container_add (GTK_CONTAINER (eventbox56), button32ajouter_aff);
  gtk_widget_set_size_request (button32ajouter_aff, 168, 44);

  eventbox57 = gtk_event_box_new ();
  gtk_widget_show (eventbox57);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox57, 16, 280);
  gtk_widget_set_size_request (eventbox57, 168, 44);

  button24modifier_aff = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (button24modifier_aff);
  gtk_container_add (GTK_CONTAINER (eventbox57), button24modifier_aff);
  gtk_widget_set_size_request (button24modifier_aff, 168, 44);

  eventbox58 = gtk_event_box_new ();
  gtk_widget_show (eventbox58);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox58, 16, 424);
  gtk_widget_set_size_request (eventbox58, 168, 44);

  button22supprimer_aff = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (button22supprimer_aff);
  gtk_container_add (GTK_CONTAINER (eventbox58), button22supprimer_aff);
  gtk_widget_set_size_request (button22supprimer_aff, 168, 44);

  image7 = create_pixmap (equipement_afficher, "afficher1.jpg");
  gtk_widget_show (image7);
  gtk_fixed_put (GTK_FIXED (fixed3), image7, 0, 0);
  gtk_widget_set_size_request (image7, 1104, 608);

  eventbox59 = gtk_event_box_new ();
  gtk_widget_show (eventbox59);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox59, 648, 208);
  gtk_widget_set_size_request (eventbox59, 88, 29);

  button44 = gtk_button_new_with_mnemonic (_("chercher"));
  gtk_widget_show (button44);
  gtk_container_add (GTK_CONTAINER (eventbox59), button44);
  gtk_widget_set_size_request (button44, 88, 29);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button29capteurs_aff, "clicked",
                    G_CALLBACK (on_button29capteurs_aff_clicked),
                    NULL);
  g_signal_connect ((gpointer) button26troupeaux_aff, "clicked",
                    G_CALLBACK (on_button26troupeaux_aff_clicked),
                    NULL);
  g_signal_connect ((gpointer) button25calendrier_aff, "clicked",
                    G_CALLBACK (on_button25calendrier_aff_clicked),
                    NULL);
  g_signal_connect ((gpointer) button28ouvrier_aff, "clicked",
                    G_CALLBACK (on_button28ouvrier_aff_clicked),
                    NULL);
  g_signal_connect ((gpointer) button27clients_aff, "clicked",
                    G_CALLBACK (on_button27clients_aff_clicked),
                    NULL);
  g_signal_connect ((gpointer) button32ajouter_aff, "clicked",
                    G_CALLBACK (on_button32ajouter_aff_clicked),
                    NULL);
  g_signal_connect ((gpointer) button24modifier_aff, "clicked",
                    G_CALLBACK (on_button24modifier_aff_clicked),
                    NULL);
  g_signal_connect ((gpointer) button22supprimer_aff, "clicked",
                    G_CALLBACK (on_button22supprimer_aff_clicked),
                    NULL);
  g_signal_connect ((gpointer) button44, "clicked",
                    G_CALLBACK (on_button44_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (equipement_afficher, equipement_afficher, "equipement_afficher");
  GLADE_HOOKUP_OBJECT (equipement_afficher, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (equipement_afficher, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (equipement_afficher, entryfiltre, "entryfiltre");
  GLADE_HOOKUP_OBJECT (equipement_afficher, eventbox51, "eventbox51");
  GLADE_HOOKUP_OBJECT (equipement_afficher, button29capteurs_aff, "button29capteurs_aff");
  GLADE_HOOKUP_OBJECT (equipement_afficher, eventbox52, "eventbox52");
  GLADE_HOOKUP_OBJECT (equipement_afficher, button26troupeaux_aff, "button26troupeaux_aff");
  GLADE_HOOKUP_OBJECT (equipement_afficher, eventbox53, "eventbox53");
  GLADE_HOOKUP_OBJECT (equipement_afficher, button25calendrier_aff, "button25calendrier_aff");
  GLADE_HOOKUP_OBJECT (equipement_afficher, eventbox54, "eventbox54");
  GLADE_HOOKUP_OBJECT (equipement_afficher, button28ouvrier_aff, "button28ouvrier_aff");
  GLADE_HOOKUP_OBJECT (equipement_afficher, eventbox55, "eventbox55");
  GLADE_HOOKUP_OBJECT (equipement_afficher, button27clients_aff, "button27clients_aff");
  GLADE_HOOKUP_OBJECT (equipement_afficher, eventbox56, "eventbox56");
  GLADE_HOOKUP_OBJECT (equipement_afficher, button32ajouter_aff, "button32ajouter_aff");
  GLADE_HOOKUP_OBJECT (equipement_afficher, eventbox57, "eventbox57");
  GLADE_HOOKUP_OBJECT (equipement_afficher, button24modifier_aff, "button24modifier_aff");
  GLADE_HOOKUP_OBJECT (equipement_afficher, eventbox58, "eventbox58");
  GLADE_HOOKUP_OBJECT (equipement_afficher, button22supprimer_aff, "button22supprimer_aff");
  GLADE_HOOKUP_OBJECT (equipement_afficher, image7, "image7");
  GLADE_HOOKUP_OBJECT (equipement_afficher, eventbox59, "eventbox59");
  GLADE_HOOKUP_OBJECT (equipement_afficher, button44, "button44");

  return equipement_afficher;
}

GtkWidget*
create_equipement_supprimer (void)
{
  GtkWidget *equipement_supprimer;
  GtkWidget *fixed4;
  GtkWidget *numsupp;
  GtkWidget *eventbox41;
  GtkWidget *button41;
  GtkWidget *eventbox42;
  GtkWidget *button36;
  GtkWidget *eventbox43;
  GtkWidget *button37;
  GtkWidget *eventbox44;
  GtkWidget *button42;
  GtkWidget *eventbox45;
  GtkWidget *button38;
  GtkWidget *eventbox46;
  GtkWidget *button34affichersupp;
  GtkWidget *eventbox47;
  GtkWidget *button43ajoutersupp;
  GtkWidget *eventbox48;
  GtkWidget *button35modifiersupp;
  GtkWidget *button56supprimer;
  GtkWidget *eventbox49;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label19;
  GtkWidget *eventbox50;
  GtkWidget *label18numdeserie_supp;
  GtkWidget *image6;

  equipement_supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (equipement_supprimer), _("espace employ\303\251"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (equipement_supprimer), fixed4);

  numsupp = gtk_entry_new ();
  gtk_widget_show (numsupp);
  gtk_fixed_put (GTK_FIXED (fixed4), numsupp, 456, 336);
  gtk_widget_set_size_request (numsupp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (numsupp), 8226);

  eventbox41 = gtk_event_box_new ();
  gtk_widget_show (eventbox41);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox41, 792, 128);
  gtk_widget_set_size_request (eventbox41, 80, 32);

  button41 = gtk_button_new_with_mnemonic (_("clients"));
  gtk_widget_show (button41);
  gtk_container_add (GTK_CONTAINER (eventbox41), button41);
  gtk_widget_set_size_request (button41, 80, 32);

  eventbox42 = gtk_event_box_new ();
  gtk_widget_show (eventbox42);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox42, 688, 128);
  gtk_widget_set_size_request (eventbox42, 80, 32);

  button36 = gtk_button_new_with_mnemonic (_("calendrier"));
  gtk_widget_show (button36);
  gtk_container_add (GTK_CONTAINER (eventbox42), button36);
  gtk_widget_set_size_request (button36, 80, 32);

  eventbox43 = gtk_event_box_new ();
  gtk_widget_show (eventbox43);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox43, 584, 128);
  gtk_widget_set_size_request (eventbox43, 80, 32);

  button37 = gtk_button_new_with_mnemonic (_("ouvrier"));
  gtk_widget_show (button37);
  gtk_container_add (GTK_CONTAINER (eventbox43), button37);
  gtk_widget_set_size_request (button37, 80, 32);

  eventbox44 = gtk_event_box_new ();
  gtk_widget_show (eventbox44);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox44, 376, 128);
  gtk_widget_set_size_request (eventbox44, 80, 32);

  button42 = gtk_button_new_with_mnemonic (_("troupeaux"));
  gtk_widget_show (button42);
  gtk_container_add (GTK_CONTAINER (eventbox44), button42);
  gtk_widget_set_size_request (button42, 80, 32);

  eventbox45 = gtk_event_box_new ();
  gtk_widget_show (eventbox45);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox45, 272, 128);
  gtk_widget_set_size_request (eventbox45, 80, 32);

  button38 = gtk_button_new_with_mnemonic (_("capteurs"));
  gtk_widget_show (button38);
  gtk_container_add (GTK_CONTAINER (eventbox45), button38);
  gtk_widget_set_size_request (button38, 80, 32);

  eventbox46 = gtk_event_box_new ();
  gtk_widget_show (eventbox46);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox46, 8, 352);
  gtk_widget_set_size_request (eventbox46, 168, 44);

  button34affichersupp = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (button34affichersupp);
  gtk_container_add (GTK_CONTAINER (eventbox46), button34affichersupp);
  gtk_widget_set_size_request (button34affichersupp, 168, 44);

  eventbox47 = gtk_event_box_new ();
  gtk_widget_show (eventbox47);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox47, 8, 208);
  gtk_widget_set_size_request (eventbox47, 168, 44);

  button43ajoutersupp = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (button43ajoutersupp);
  gtk_container_add (GTK_CONTAINER (eventbox47), button43ajoutersupp);
  gtk_widget_set_size_request (button43ajoutersupp, 168, 44);

  eventbox48 = gtk_event_box_new ();
  gtk_widget_show (eventbox48);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox48, 8, 280);
  gtk_widget_set_size_request (eventbox48, 168, 44);

  button35modifiersupp = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (button35modifiersupp);
  gtk_container_add (GTK_CONTAINER (eventbox48), button35modifiersupp);
  gtk_widget_set_size_request (button35modifiersupp, 168, 44);

  button56supprimer = gtk_button_new ();
  gtk_widget_show (button56supprimer);
  gtk_fixed_put (GTK_FIXED (fixed4), button56supprimer, 448, 448);
  gtk_widget_set_size_request (button56supprimer, 136, 48);

  eventbox49 = gtk_event_box_new ();
  gtk_widget_show (eventbox49);
  gtk_container_add (GTK_CONTAINER (button56supprimer), eventbox49);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (eventbox49), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox1), label19, FALSE, FALSE, 0);

  eventbox50 = gtk_event_box_new ();
  gtk_widget_show (eventbox50);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox50, 272, 328);
  gtk_widget_set_size_request (eventbox50, 153, 40);

  label18numdeserie_supp = gtk_label_new (_("numero de serie"));
  gtk_widget_show (label18numdeserie_supp);
  gtk_container_add (GTK_CONTAINER (eventbox50), label18numdeserie_supp);
  gtk_widget_set_size_request (label18numdeserie_supp, 153, 40);

  image6 = create_pixmap (equipement_supprimer, "supprimr2.jpg");
  gtk_widget_show (image6);
  gtk_fixed_put (GTK_FIXED (fixed4), image6, 0, 0);
  gtk_widget_set_size_request (image6, 1088, 608);

  g_signal_connect ((gpointer) button34affichersupp, "clicked",
                    G_CALLBACK (on_button34affichersupp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button43ajoutersupp, "clicked",
                    G_CALLBACK (on_button43ajoutersupp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button35modifiersupp, "clicked",
                    G_CALLBACK (on_button35modifiersupp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button56supprimer, "clicked",
                    G_CALLBACK (on_button56supprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (equipement_supprimer, equipement_supprimer, "equipement_supprimer");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, numsupp, "numsupp");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, eventbox41, "eventbox41");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, button41, "button41");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, eventbox42, "eventbox42");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, button36, "button36");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, eventbox43, "eventbox43");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, button37, "button37");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, eventbox44, "eventbox44");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, button42, "button42");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, eventbox45, "eventbox45");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, button38, "button38");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, eventbox46, "eventbox46");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, button34affichersupp, "button34affichersupp");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, eventbox47, "eventbox47");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, button43ajoutersupp, "button43ajoutersupp");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, eventbox48, "eventbox48");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, button35modifiersupp, "button35modifiersupp");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, button56supprimer, "button56supprimer");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, eventbox49, "eventbox49");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, image1, "image1");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, label19, "label19");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, eventbox50, "eventbox50");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, label18numdeserie_supp, "label18numdeserie_supp");
  GLADE_HOOKUP_OBJECT (equipement_supprimer, image6, "image6");

  return equipement_supprimer;
}

GtkWidget*
create_capteurs_alarmants (void)
{
  GtkWidget *capteurs_alarmants;
  GtkWidget *fixed5;
  GtkWidget *label31;
  GtkWidget *treeview2;
  GtkWidget *treeview3;
  GtkObject *spinbutton13_adj;
  GtkWidget *spinbutton13;
  GtkObject *spinbutton14_adj;
  GtkWidget *spinbutton14;
  GtkObject *spinbutton15_adj;
  GtkWidget *spinbutton15;
  GtkObject *spinbutton16_adj;
  GtkWidget *spinbutton16;
  GtkObject *spinbutton17_adj;
  GtkWidget *spinbutton17;
  GtkObject *spinbutton18_adj;
  GtkWidget *spinbutton18;
  GtkWidget *eventbox60;
  GtkWidget *button54ajouterentr;
  GtkWidget *eventbox61;
  GtkWidget *button46modifierentr;
  GtkWidget *image8;
  GtkWidget *eventbox62;
  GtkWidget *button53troupeauxentr;
  GtkWidget *eventbox63;
  GtkWidget *button52clentsentr;
  GtkWidget *eventbox64;
  GtkWidget *button49capteursentr;
  GtkWidget *eventbox65;
  GtkWidget *button48ouvrierentr;
  GtkWidget *eventbox66;
  GtkWidget *button47calendrierentr;
  GtkWidget *eventbox67;
  GtkWidget *button45afficherentr;
  GtkWidget *eventbox68;
  GtkWidget *button44supprimerentr;
  GtkWidget *eventbox69;
  GtkWidget *button45hum;
  GtkWidget *eventbox70;
  GtkWidget *button43temp;
  GtkWidget *eventbox71;
  GtkWidget *button46plus;

  capteurs_alarmants = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (capteurs_alarmants), _("espace employ\303\251"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (capteurs_alarmants), fixed5);

  label31 = gtk_label_new ("");
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed5), label31, 416, 328);
  gtk_widget_set_size_request (label31, 160, 32);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview2, 192, 288);
  gtk_widget_set_size_request (treeview2, 300, 200);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview3, 512, 288);
  gtk_widget_set_size_request (treeview3, 300, 200);

  spinbutton13_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton13 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton13_adj), 1, 0);
  gtk_widget_show (spinbutton13);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton13, 216, 248);
  gtk_widget_set_size_request (spinbutton13, 60, 27);

  spinbutton14_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton14 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton14_adj), 1, 0);
  gtk_widget_show (spinbutton14);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton14, 312, 248);
  gtk_widget_set_size_request (spinbutton14, 60, 27);

  spinbutton15_adj = gtk_adjustment_new (1, 2020, 2050, 1, 10, 10);
  spinbutton15 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton15_adj), 1, 0);
  gtk_widget_show (spinbutton15);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton15, 400, 248);
  gtk_widget_set_size_request (spinbutton15, 60, 27);

  spinbutton16_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton16 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton16_adj), 1, 0);
  gtk_widget_show (spinbutton16);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton16, 536, 248);
  gtk_widget_set_size_request (spinbutton16, 60, 27);

  spinbutton17_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton17 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton17_adj), 1, 0);
  gtk_widget_show (spinbutton17);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton17, 624, 248);
  gtk_widget_set_size_request (spinbutton17, 60, 27);

  spinbutton18_adj = gtk_adjustment_new (1, 2020, 2050, 1, 10, 10);
  spinbutton18 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton18_adj), 1, 0);
  gtk_widget_show (spinbutton18);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton18, 712, 248);
  gtk_widget_set_size_request (spinbutton18, 60, 27);

  eventbox60 = gtk_event_box_new ();
  gtk_widget_show (eventbox60);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox60, 8, 208);
  gtk_widget_set_size_request (eventbox60, 168, 40);

  button54ajouterentr = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (button54ajouterentr);
  gtk_container_add (GTK_CONTAINER (eventbox60), button54ajouterentr);
  gtk_widget_set_size_request (button54ajouterentr, 168, 40);

  eventbox61 = gtk_event_box_new ();
  gtk_widget_show (eventbox61);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox61, 8, 272);
  gtk_widget_set_size_request (eventbox61, 168, 40);

  button46modifierentr = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (button46modifierentr);
  gtk_container_add (GTK_CONTAINER (eventbox61), button46modifierentr);
  gtk_widget_set_size_request (button46modifierentr, 168, 40);

  image8 = create_pixmap (capteurs_alarmants, "vqleur.jpg");
  gtk_widget_show (image8);
  gtk_fixed_put (GTK_FIXED (fixed5), image8, 0, 0);
  gtk_widget_set_size_request (image8, 1096, 600);

  eventbox62 = gtk_event_box_new ();
  gtk_widget_show (eventbox62);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox62, 488, 128);
  gtk_widget_set_size_request (eventbox62, 72, 28);

  button53troupeauxentr = gtk_button_new_with_mnemonic (_("troupeaux"));
  gtk_widget_show (button53troupeauxentr);
  gtk_container_add (GTK_CONTAINER (eventbox62), button53troupeauxentr);
  gtk_widget_set_size_request (button53troupeauxentr, 72, 28);

  eventbox63 = gtk_event_box_new ();
  gtk_widget_show (eventbox63);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox63, 800, 128);
  gtk_widget_set_size_request (eventbox63, 72, 28);

  button52clentsentr = gtk_button_new_with_mnemonic (_("clients"));
  gtk_widget_show (button52clentsentr);
  gtk_container_add (GTK_CONTAINER (eventbox63), button52clentsentr);
  gtk_widget_set_size_request (button52clentsentr, 72, 28);

  eventbox64 = gtk_event_box_new ();
  gtk_widget_show (eventbox64);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox64, 384, 128);
  gtk_widget_set_size_request (eventbox64, 72, 28);

  button49capteursentr = gtk_button_new_with_mnemonic (_("equipements"));
  gtk_widget_show (button49capteursentr);
  gtk_container_add (GTK_CONTAINER (eventbox64), button49capteursentr);
  gtk_widget_set_size_request (button49capteursentr, 72, 28);

  eventbox65 = gtk_event_box_new ();
  gtk_widget_show (eventbox65);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox65, 592, 128);
  gtk_widget_set_size_request (eventbox65, 72, 28);

  button48ouvrierentr = gtk_button_new_with_mnemonic (_("ouvrier"));
  gtk_widget_show (button48ouvrierentr);
  gtk_container_add (GTK_CONTAINER (eventbox65), button48ouvrierentr);
  gtk_widget_set_size_request (button48ouvrierentr, 72, 28);

  eventbox66 = gtk_event_box_new ();
  gtk_widget_show (eventbox66);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox66, 696, 128);
  gtk_widget_set_size_request (eventbox66, 72, 28);

  button47calendrierentr = gtk_button_new_with_mnemonic (_("calendrier"));
  gtk_widget_show (button47calendrierentr);
  gtk_container_add (GTK_CONTAINER (eventbox66), button47calendrierentr);
  gtk_widget_set_size_request (button47calendrierentr, 72, 28);

  eventbox67 = gtk_event_box_new ();
  gtk_widget_show (eventbox67);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox67, 8, 344);
  gtk_widget_set_size_request (eventbox67, 168, 40);

  button45afficherentr = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (button45afficherentr);
  gtk_container_add (GTK_CONTAINER (eventbox67), button45afficherentr);
  gtk_widget_set_size_request (button45afficherentr, 168, 40);

  eventbox68 = gtk_event_box_new ();
  gtk_widget_show (eventbox68);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox68, 8, 416);
  gtk_widget_set_size_request (eventbox68, 168, 40);

  button44supprimerentr = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (button44supprimerentr);
  gtk_container_add (GTK_CONTAINER (eventbox68), button44supprimerentr);
  gtk_widget_set_size_request (button44supprimerentr, 168, 40);

  eventbox69 = gtk_event_box_new ();
  gtk_widget_show (eventbox69);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox69, 608, 184);
  gtk_widget_set_size_request (eventbox69, 122, 53);

  button45hum = gtk_button_new_with_mnemonic (_("alarmant hum"));
  gtk_widget_show (button45hum);
  gtk_container_add (GTK_CONTAINER (eventbox69), button45hum);
  gtk_widget_set_size_request (button45hum, 122, 53);

  eventbox70 = gtk_event_box_new ();
  gtk_widget_show (eventbox70);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox70, 280, 192);
  gtk_widget_set_size_request (eventbox70, 120, 48);

  button43temp = gtk_button_new_with_mnemonic (_("alarmant temp"));
  gtk_widget_show (button43temp);
  gtk_container_add (GTK_CONTAINER (eventbox70), button43temp);
  gtk_widget_set_size_request (button43temp, 120, 48);

  eventbox71 = gtk_event_box_new ();
  gtk_widget_show (eventbox71);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox71, 432, 520);
  gtk_widget_set_size_request (eventbox71, 128, 45);

  button46plus = gtk_button_new_with_mnemonic (_("plus alarmants"));
  gtk_widget_show (button46plus);
  gtk_container_add (GTK_CONTAINER (eventbox71), button46plus);
  gtk_widget_set_size_request (button46plus, 128, 45);

  g_signal_connect ((gpointer) button45hum, "clicked",
                    G_CALLBACK (on_button45hum_clicked),
                    NULL);
  g_signal_connect ((gpointer) button43temp, "clicked",
                    G_CALLBACK (on_button43temp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button46plus, "clicked",
                    G_CALLBACK (on_button46plus_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (capteurs_alarmants, capteurs_alarmants, "capteurs_alarmants");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, label31, "label31");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, spinbutton13, "spinbutton13");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, spinbutton14, "spinbutton14");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, spinbutton15, "spinbutton15");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, spinbutton16, "spinbutton16");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, spinbutton17, "spinbutton17");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, spinbutton18, "spinbutton18");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, eventbox60, "eventbox60");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, button54ajouterentr, "button54ajouterentr");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, eventbox61, "eventbox61");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, button46modifierentr, "button46modifierentr");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, image8, "image8");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, eventbox62, "eventbox62");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, button53troupeauxentr, "button53troupeauxentr");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, eventbox63, "eventbox63");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, button52clentsentr, "button52clentsentr");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, eventbox64, "eventbox64");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, button49capteursentr, "button49capteursentr");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, eventbox65, "eventbox65");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, button48ouvrierentr, "button48ouvrierentr");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, eventbox66, "eventbox66");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, button47calendrierentr, "button47calendrierentr");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, eventbox67, "eventbox67");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, button45afficherentr, "button45afficherentr");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, eventbox68, "eventbox68");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, button44supprimerentr, "button44supprimerentr");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, eventbox69, "eventbox69");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, button45hum, "button45hum");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, eventbox70, "eventbox70");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, button43temp, "button43temp");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, eventbox71, "eventbox71");
  GLADE_HOOKUP_OBJECT (capteurs_alarmants, button46plus, "button46plus");

  return capteurs_alarmants;
}

